<?php $list_data = array (
  0 => 
  array (
    0 => 'Banner Text',
    1 => 'SEE 👀',
    2 => 'MUSIC 🎶',
    3 => 'EAT 🍽 & DRINK 🍹',
    4 => 'DANCE 👟 👟',
    5 => 'WATCH 🎥',
    6 => 'LISTEN 🎧',
    7 => 'OUTDOORS 🌳',
    8 => 'SHOP 🛒',
    9 => 'THINK 🤔',
  ),
  1 => 
  array (
    0 => 'A list of stuff that\'s on in NYC - Updated 7/10/2017',
    1 => '[url=http://www.metmuseum.org/exhibitions/listings/2017/rei-kawakubo]Rei Kawakubo/ Comme des Garcons/ Art of the In-Between[/url] show at the Met, and [url=http://www.metmuseum.org/exhibitions/listings/2017/irving-penn-centennial]Irving Penn Centenial[/url] - it\'s worth braving the crowds.',
    2 => 'Wed, Jul 11 [url=http://www.cityparksfoundation.org/event/mon-laferte-princess-nokia-ife-association-latin-alternative-music-conference/]Princess Nokia[/url] is playing a FREE show at Central Park Summer stage.',
    3 => 'Jul 14 - Aug 18, [url=https://www.nycgo.com/restaurant-week]Reservations for restaurant week[/url] have just openned - get fixed price dinners ($42) and lunches ($29) at $$$$ restaurants.',
    4 => 'Fri, July 14 Stay up dancing all night to [url=https://www.ticketfly.com/purchase/event/1515068]Sophie and Umfang at Goodroom[/url]. Tickets on sale now.',
    5 => 'There are a few good movies out at the moment:',
    6 => 'Some new pod food for your ears!',
    7 => '[url=https://www.nybg.org/event/chihuly/]Dale Chihuly[/url] at New York Botanic Gardens.',
    8 => 'Jul 20 - 23, Kendrick Lamar is launching a series of [url=http://thedamnpopup.com]pop up shops[/url] around the US for exclusive DAMN merch. The NY one is at 39 Spring st.',
    9 => 'It\'s the 2nd year of the [url=https://www.eventbrite.com/e/likeminds-20-tickets-35362516238]Likeminds[/url] camping conference in upstate NY. Early bird tickets now on sale.',
  ),
  2 => 
  array (
    0 => '',
    1 => '[url=https://www.gagosian.com/exhibitions/carsten-holler--june-20-2017]Carsten Höller[/url] show at the Gasgonian has it all with giant mushrooms, mirrored revolving doors, abstract paintings, hyperreal little fishes, and huge dice.',
    2 => 'Sun, Jul 16 FREE [url=http://www.cityparksfoundation.org/event/fela-tribute-roy-ayers-seun-kuti-egypt-80-underground-system-rich-medina-association-giant-step/]tribute show to the great Fela Kuti[/url] with greats like [url=https://open.spotify.com/artist/6R9Mv0bgGE4Tqxna1q5Mrj]Roy Ayers[/url], [url=https://open.spotify.com/album/3St6Cw46SBtFnIURclQ6yV]Seun Kuti & the Egypt 80[/url] and more at Central Park Summer stage. Time to [url=https://open.spotify.com/track/6ghe4sMRzup1cOu7TyEztf]get down in the sunshine[/url]. ',
    3 => 'Sat Jul 23, Yes that\'s right it\'s a freaking [url=https://jerkfestivalny.com/]Jamaican Jerk Festival[/url] in Queens!!! Sample the best jerk in town.',
    4 => 'Sat, July 15 Jacques Green/ Offline Projects and RINSED present [url=http://rinsed.it/events/rinsed-love-hotel/]Love Hotel[/url]. They are building a 3 floor hotel with different tunes on each level, private rooms to hire by the hour, and robe hire. Yes sounds a lot like an orgy - careful out there....👩‍❤️‍💋‍👩  Early bird tickets on sale now.',
    5 => '[url=https://www.youtube.com/watch?v=z2z857RSfhk]Baby Driver[/url] featuring an all star cast and a killer soundtrack is an all round great action flic. 👶 🚗',
    6 => 'Abbi from Broad City is hosting a new podcast with WNYC and MoMA on art called [url=http://www.wnyc.org/shows/pieceofwork]A Piece of Work[/url]. The first ep features fellow comedian and Broad City star Hannibal Buress.',
    7 => 'Venture up to [url=http://stormking.org/visit/]Storm King[/url], as well as seeing the sculptures you can take a [url=http://stormking.org/events/beekeeper-tours-3-2017-07-01/] bee keeping tour [/url] 🐝.',
    8 => '',
    9 => 'Tues, Aug 8 The infamous athiest [url=https://www.92y.org/event/richard-dawkins-with-dave-rubin]Richard Dawkins[/url] will be speaking at 92Y on his new book [i]Science in the Soul[/i]. Tickets on sale now.',
  ),
  3 => 
  array (
    0 => '',
    1 => '[url=http://www.armoryonpark.org/programs_events/detail/hansel_gretel]Hansel &Gretel[/url] is a new show by Pritzker Prize-winning architects Jacques Herzog and Pierre de Meuron and artist/activist Ai Weiwei just openned at the Park Armory.',
    2 => 'Fri, Jul 21 [url=https://www.bricartsmedia.org/events-performances/bric-celebrate-brooklyn-festival/amadou-mariam-innov-gnawa-ahmed-gallab-dj-set]Amadou & Mariam and Innov Gnawa[/url] are playing at Prospect Park Band Shell for BRIC Festival. [url=https://open.spotify.com/album/2pWLCYxSA5Us753JIjK8lX]Amadou & Mariam[/url] are a seriously funky musical duo from Mali, and they are both bilnd. And you might know Innov Gnawa from their [url=https://open.spotify.com/album/4Ui5FMje2UiaVPf6XmveUN]collab with Floating Points[/url].',
    3 => '[url=http://dekalbmarkethall.com/#vendors]Dekalb Market Hall[/url] just openned up in Brooklyn and it seriously has ALL the best food. Check it out in Downtown BK.',
    4 => 'There are only camping tickets left for [url=http://www.sustain-release.com/]Sustain Release YEAR 4[/url], they go on sale Jul 11 at 2PM.',
    5 => '[url=https://www.youtube.com/watch?v=GX3Regj6nAg]The Big Sick[/url] is the new rom com everyone is talking about with Kumail Nanjiani from Silicon Valley. 💑',
    6 => '[url=https://www.earhustlesq.com/]Ear Hustle[/url] is a new podcast about life behind bars, created and produced by actual inmates of San Quentin. This won [url=https://www.radiotopia.fm/podquest]Radiotopia\'s podquest[/url] last year, it\'s def worth a listen.',
    7 => 'A house full of [url=https://www.diaart.org/visit/visit/the-dan-flavin-art-institute-bridgehampton-united-states]Dan Flavin[/url], but you have to trek up to [url=https://www.google.com/maps/place/23+Corwith+Ave,+Bridgehampton,+NY+11932/data=!4m2!3m1!1s0x89e8bddf84640b55:0x6306b479e94d2c9d?sa=X&ved=0ahUKEwiDj8OaxtfUAhVIrD4KHZ9XDrcQ8gEIJzAA] Bridgehampton[/url].',
    8 => '',
    9 => '',
  ),
  4 => 
  array (
    0 => '',
    1 => 'Openning Wed, Aug 2 [url=https://www.fridmangallery.com/a-becoming-resemblance]A Becoming Resemblance[/url] by Heather Dewey-Hagborg & Chelsea Manning features 3D printed portraits from the DNA samples from Chelsea mailed out of prison. At the Fridman Gallery.',
    2 => 'Thurs, Aug 17 [url=https://www.residentadvisor.net/event.aspx?982256]Photay\'s Album Launch Release Party[/url] at Baby\'s Alright. Here\'s a [url=spotify:track:4QeRFvicL7zcuVVjRa6UhX]taste[/url].',
    3 => '[url=http://the-meathook.com/bbq/]The Meat Hook[/url] in WB are doing BBQs every Wed night from 6PM - 9PM, feat. good meat from local farms.',
    4 => '',
    5 => '[url=https://www.youtube.com/watch?v=c_3NMtxeyfk]A Ghost Story[/url], about a married couple - Rooney Mara and Casey Affleck. The husband dies and comes back as a ghost literally in a white sheet. WARNING: Looks like a real tearjerker. 👻',
    6 => '',
    7 => '',
    8 => '',
    9 => '',
  ),
  5 => 
  array (
    0 => '',
    1 => '',
    2 => 'Wed, Oct 11 [url=https://www.axs.com/artists/251590/moses-sumney-tickets]Moses Sumney[/url] is playing a WB Music Hall. You can get tickets on presale now with the code: Moses',
    3 => '',
    4 => '',
    5 => '',
    6 => '',
    7 => '',
    8 => '',
    9 => '',
  ),
); ?>